# Script Config info
walletID: ''

# currecy codes must match ISO 4217
currencyCode: 'USD'

serverLogs: true
serverLogDirectory: ''
serverLogLevel: 'INFO'

twilioAPIKey: ''
twilioAccount: ''
destinationPhone: ''
twilioPhone: ''

sendgridAPIKey: ''
destinationEmail: ''
sendgridEmail: ''
emailWithImage: 'True'
